[profile.default]
src = "src"
test = "test/forge"
evm_version = "paris"
fs_permissions = [
    { access = "read", path = "./config/"},
    { access = "read", path = "./lib/morpho-blue/out/"}
]
libs = ["node_modules", "lib"]

[profile.default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"
tenderly = "https://rpc.tenderly.co/fork/${TENDERLY_FORK_ID}"

[profile.default.fmt]
wrap_comments = true


[profile.build]
via-ir = true
test = "/dev/null"
script = "/dev/null"


[profile.test]
via-ir = false


# See more config options https://github.com/foundry-rs/foundry/tree/master/config
